### ISSUE TITLE
dDGPU OFF

### ISSUE THREAD

**Issue by bouhka** [LuckyCrack/Legion-5i-EFI#1]
HI,I have a legion 5i 10750h with big sur but i cannot turn off dGPU gtx1660ti, did you get it turn it off? how long does the battery last in hackintosh? the official dortania methods cannot turn it off. thank you.

**Comment by LuckyCrack** [comment]
You can try -wegnoegpu or maybe nv_disable=1 boot args to disable dgpu but i never used these boot args and still managed to boot as this card will not be recognized by mac.
And i always use my laptop plugged-in so i don't know about the battery life in mac, its probably OK-ish.
